version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    branches:
      ignore: gh-pages
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install pipenv --upgrade
            pipenv install --dev
      - run:
          name: build data
          command: pipenv run build
      - run:
          name: run tests
          command: pipenv run test
      - run:
          name: build HTML
          command: pipenv run freeze
      - run:
          name: deploy
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              # https://github.com/pyvec/elsa/pull/65
              export TRAVIS=1
              export TRAVIS_REPO_SLUG=pyvec/pyvec.org

              # run Elsa
              pipenv run deploy
            fi
